import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link href="/posts">
            <button>take me to posts page</button>
          </Link>
          <Link href="/articles">
            <button>take me to articles page</button>
          </Link>
          <Link href="/articles/title">
            <button>take me to article page</button>
          </Link>
          <Link href="/articles/featuredArticles">
            <button>take me to featured Articles page</button>
          </Link>
          <Link href="/">
            <button>take me to Home page</button>
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
